version: '3'

services:
  dev-api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    command: ["flask", "run", "--host=0.0.0.0", "--debug"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  dev-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - dev-api

volumes:
  node-modules: